export const REQUEST_TRACKS = "REQUEST_TRACKS";
export const RECEIVE_TRACKS = "RECIEVE_TRACKS";
export const REQUEST_RECOMMENDATIONS = "REQUEST_RECOMMENDATIONS";
export const RECEIVE_RECOMMENDATIONS = "RECEIVE_RECOMMENDATIONS";
export const SELECT_TRACKS = "SELECT_TRACKS";