export const REQUEST_AUTH = "REQUEST_AUTH";
export const RECEIVE_AUTH = "RECEIVE_AUTH";
export const FAIL_AUTH = "FAIL_AUTH";
export const REQUEST_TRACKS = "REQUEST_TOP";
export const RECEIVE_TRACKS = "RECIEVE_TOP";
export const REQUEST_RECOMMENDATIONS = "REQUEST_RECOMMENDATIONS";
export const RECEIVE_RECOMMENDATIONS = "RECEIVE_RECOMMENDATIONS";
export const SELECT_TRACKS = "SELECT_TRACKS";